language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"
  npm: true

services: mongodb

before_script:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - go get github.com/jpmonette/apexcov
  - ./cc-test-reporter before-build
  - echo "" >> .env

script:
  - npm run coverage:server

after_script:
  - apexcov
  - ./cc-test-reporter format-coverage -t lcov ./server/coverage/lcov.info
  - ./cc-test-reporter upload-coverage
