language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"
  npm: true

services: mongodb

before_script:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - echo "" >> .env

script:
  - npm run coverage:server

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
